blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a Question
    url: https://github.com/NiklasDerEchte/angular-express-app/discussions
    about: Use GitHub Discussions for general questions or help.
